# Dependencies
markdown:         kramdown
highlighter:      rouge

    # Permalinks
permalink:        pretty

    # Setup
title:            Alex Mülli
tagline:          'Personal Blog'
description:      'MSc in Computer Science'
url:              http://amuelli.github.io
baseurl:          /
timezone:         Europe/Zurich

author:
    name:           'Alex Mülli'
    email:          amuelli@gmail.com
    twitter:        https://twitter.com/AlexMulli/
    github:         https://github.com/amuelli/
    linkedin:       http://ch.linkedin.com/pub/alexander-m%c3%bclli/35/b64/895/

paginate:         5
